downstream_expert:
  datarc:
    eval_batch_size: 32
    file_path: /workspace/s3prl_copy/s3prl/data/fluent_speech_commands_dataset
    num_workers: 12
    train_batch_size: 32
  modelrc:
    UtteranceLevel:
      pooling: MeanPooling
    projector_dim: 256
    select: UtteranceLevel
optimizer:
  lr: 0.0001
  name: TorchOptim
  torch_optim_name: Adam
runner:
  eval_dataloaders:
  - dev
  - test
  eval_step: 5000
  gradient_accumulate_steps: 1
  gradient_clipping: 1
  log_step: 100
  max_keep: 1
  save_step: 250
  total_steps: 200000
